version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tax-yo-pants"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-92huu4abc6s5"
s3_prefix = "tax-yo-pants"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["ShipYoPants=104823389718.dkr.ecr.us-east-1.amazonaws.com/samapp7427b055/shipyopants3e71219arepo"]
