version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "heartland-taxyopants"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bto2jbqv73is"
s3_prefix = "heartland-taxyopants"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["TaxYoPants=464570369687.dkr.ecr.us-east-1.amazonaws.com/heartlandtaxyopants76c83060/taxyopants8251c9derepo"]
