AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  heartland-shipyopants

  Sample SAM Template for heartland-shipyopants
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  ShipYoPants:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - 
          SSMParameterReadPolicy:
            ParameterName: TAX_JAR_API_KEY_SB
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        CalculateSalesTax:
          Type: Api
          Properties:
            Path: /tax-service/calculate-sales-tax
            Method: post
    Metadata:
      DockerTag: nodejs12.x-v1
      DockerContext: ./shipyopants
      Dockerfile: Dockerfile


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ShipYoPantsApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ShipYoPantsFunc:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ShipYoPants.Arn
  ShipYoPantsIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ShipYoPantsRole.Arn
